Logic
OptimumDev/Natural-selected-cards pull request #14
Opened 2020-05-04 07:32 UTC by qkeypechenka

closes #3

2020-05-04 07:33 UTC, qkeypechenka commented
мержить после Димы, тут есть часть изменений из его ветки

2020-05-04 10:15 UTC, OptimumDev requested changes
Есть что поправить)

2020-05-04 10:15 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Models/CardModel.cs
> +    public class CardModel
У тебя сейчас `CardModel` - полная копия сущности из базы данных, хотя идея была в том, что мы с этими данными соберем статистику для колоды. Давай в карточке оставим только `Id`, `Question` и `Answer`

2020-05-04 10:15 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Models/DeckModel.cs
> +    public class DeckModel
А вот здесь как раз таки нужна статистика:
 - кол-во карт в колоде, 
 - кол-во игр, 
 - «рейтинг» (тип насколько хорош пользователь, число от 0 до 1)
 - время последней тренировки

Высчитывать их будем соответсвенно пробегая по карточкам колоды

Можешь посмотреть в ПР Андрея, как он их назвал, я его пока не смерджил, но сегодня собираюсь

Поле `UserId` не нужно

2020-05-04 10:15 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +    public interface IDeckManager
1. Boolean - объектная обертка над примитивом bool, лучше использовать примитив
2. Принято все методы, которые возвращают Task, называть с суффиксом `Async`
3. Добавь методы для создания карточки (пустой), обновления надписей на карточке и удаления карточки
4. Во всех методах кроме `AddStandartDeck`, `AddDeck` и создании карточки `userId` вроде не нужен
5. `AddStandartDeck` лучше назвать `CopyDeck` или как-то похоже так как он не только стандартные колоды умеет копировать (в теории)
6. При создании колоды и карточки они создаются пустые - не думаю что тут нужна колода/карточка как аргумент, а возвращать достаточно Id
7. В `AddStandartDeck` и `UpdateDeck` корлода в ответе в целом не нужна, тут можно возвращать некий индикатор успешности (сейчас у тебя это bool, пока норм, если не хватит, придумаем какой-нибудь энамчик

2020-05-05 09:15 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Models/CardModel.cs
> +    public class CardModel
done

2020-05-05 09:15 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Models/DeckModel.cs
> +    public class DeckModel
done

2020-05-05 09:15 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +    public interface IDeckManager
done

2020-05-05 09:34 UTC, OptimumDev reviewed
Пару моментов пропустил

2020-05-05 09:34 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> AddDeckAsync(Guid userId, DeckModel deck);
Колода создается пустая, `DeckModel` как аргумент не нужен. При этом возвращать нужно `Guid` - как иначе потом к этой колоде обращаться?)

У тебя сейчас есть `AddDeckAsync` и `CreateCardAsync` предлагаю оба назвать либо `Add` либо `Create`

2020-05-05 09:34 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> UpdateCardKnowledgeAsync(Guid userId, Guid cardId, Boolean isCorrect);
`userId` не нужен

2020-05-05 09:34 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<CardModel> CreateCardAsync(Guid deckId);
Достаточно вернуть `Guid`

2020-05-05 09:34 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<CardModel> UpdateCardTitleAsync(Guid cardId, String title);
`Title` - это у колоды, у карточки - `Question` и `Answer`

Лучше просто оставь `UpdateCardAsync`

Тут тоже можно просто `bool` вернуть

2020-05-05 09:34 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> UpdateDeckAsync(DeckModel deck);
Здесь кстати лучше как раз сделать `UpdateDeckTitleAsync` и принимать `deckId` и `title`

2020-05-05 09:40 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> UpdateDeckAsync(DeckModel deck);
done

2020-05-05 09:40 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<CardModel> UpdateCardTitleAsync(Guid cardId, String title);
done

2020-05-05 09:40 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<CardModel> CreateCardAsync(Guid deckId);
done

2020-05-05 09:40 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> UpdateCardKnowledgeAsync(Guid userId, Guid cardId, Boolean isCorrect);
done

2020-05-05 09:41 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> AddDeckAsync(Guid userId, DeckModel deck);
done, сделал add общим

2020-05-05 09:42 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> UpdateCardAsync(Guid cardId, CardModel cardModel);
В `CardModel` уже вроде есть `Id`?

2020-05-05 09:44 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/IDeckManager.cs
> +        Task<bool> UpdateCardAsync(Guid cardId, CardModel cardModel);
да, есть, ща уберу тут

2020-05-05 09:45 UTC, OptimumDev approved these changes
Четко

2020-05-05 09:52 UTC, OptimumDev approved these changes

2020-05-05 09:53 UTC, merged