Logic
OptimumDev/Natural-selected-cards pull request #23
Opened 2020-05-09 05:05 UTC by qkeypechenka

resolves #10

2020-05-09 07:23 UTC, OptimumDev requested changes
Я подчистил код

Сделай статистику и норм. Подбор карточек и проверку ошибок сделаем отдельным ищью

2020-05-09 07:23 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return decks.ConvertAll(deck => deckMapper.Map(deck));
Здесь нужно посчитать статистику: достать карточки и за один проход по ним собрать все данные. По-хорошему это нужно сделать параллельно наверное... @Belianin что думаешь? 

Если будут проблемы с параллельностью, можешь мне написать, подумаем вместе. Думаю тут PLINQ неплохо зайдет

2020-05-09 07:23 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return decks.ConvertAll(deck => deckMapper.Map(deck));
Здесь еще собрать количество карточек

2020-05-09 07:23 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            // TODO: шафлить и фильтровать карточки
Сделаем отдельный ищью

2020-05-09 07:23 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +                entity.LastRepeat
Предлагаю в таком случае обнулять статистику, так как карточка то поменялась

2020-05-09 07:23 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return true;
```suggestion
            return result != null;
```

2020-05-09 07:23 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Mappers/CardMapper.cs
> +            model.Answer = entity.Answer;
```suggestion
            var model = new CardModel
            {
                Id = entity.Id,
                Question = entity.Question,
                Answer = entity.Answer
            };
```

2020-05-09 07:23 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Mappers/DeckMapper.cs
> +            model.Title = entity.Title;
```suggestion
            var model = new DeckModel
            {
                Id = entity.Id,
                Title = entity.Title
            }
```

2020-05-09 07:26 UTC, OptimumDev requested changes

2020-05-09 07:26 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            var result = await deckRepository.InsertAsync(deck);
Здесь у колоды должен быть новый новый `id` и `userId` из аргументов
Так же нужно перекопировать карточки (опять же желательно параллельно)

2020-05-09 07:26 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            var result = await deckRepository.InsertAsync(deck);
Здесь у колоды должен быть новый новый `id` и `userId` из аргументов

Так же нужно перекопировать карточки (опять же желательно параллельно)

2020-05-09 10:00 UTC, Belianin commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return decks.ConvertAll(deck => deckMapper.Map(deck));
Мне кажется, что это может быть не критичным. PLINQ норм, но по хорошему нужно забирать данные из БД одним батчем. Я не знаю есть ли такое в монге, но вообще должно. Самое дорогое же это запрос, вот его и нужно сделать единственным

2020-05-09 10:25 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return decks.ConvertAll(deck => deckMapper.Map(deck));
Ну тогда нужно расширять репозиторий и я не знаю о таких умениях монги... я сейчас понял, что это в целом только 2 запроса, так что действительно не критично и параллельность особо не поможет (у меня в голове почему-то было что нужно каждую карточку отдельно просить)

2020-05-09 10:27 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return decks.ConvertAll(deck => deckMapper.Map(deck));
@qkeypechenka тогда просто пробегаем карточки в цикле и собираем все что нужно)

2020-05-09 10:29 UTC, OptimumDev commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            var result = await deckRepository.InsertAsync(deck);
а вот здесь точно параллельно надо будет, карточки будут добавляться в бд по одной

2020-05-13 06:06 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return decks.ConvertAll(deck => deckMapper.Map(deck));
пока не придумал как по-хорошему рейтинг колоды собирать, в следующем таске сделаю

2020-05-13 06:06 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            return decks.ConvertAll(deck => deckMapper.Map(deck));
done

2020-05-13 06:06 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +                entity.LastRepeat
done

2020-05-13 06:06 UTC, qkeypechenka commented on NaturalSelectedCards/Logic/Managers/DeckManager.cs
> +            var result = await deckRepository.InsertAsync(deck);
done

2020-05-13 14:41 UTC, OptimumDev reviewed
Хорошо, сейчас почищу код и вмерджу

2020-05-13 14:58 UTC, OptimumDev approved these changes

2020-05-13 14:58 UTC, merged