Backend logic using
OptimumDev/Natural-selected-cards pull request #29
Opened 2020-05-14 17:23 UTC by Belianin

closes #26

2020-05-14 19:24 UTC, OptimumDev requested changes
Сейчас оч неохто смотреть, те ли ты методы дергаешь в логике, завтра посмотрю повнимательнее.

2020-05-14 19:24 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/UserController.cs
> +            await users.InsertAsync(userEntity).ConfigureAwait(false);
ненене это точно не правильно

Во первых, пользователи хранятся по `googleId` а не токену
Во вторых, если делать это тут,  то нужен апсерт

Я вообще думал, что мы будем в хэнделере проверять, что если в бд нет пользователя - создавать

2020-05-15 14:31 UTC, OptimumDev reviewed
Проверил дополнительно

Вроде если не возвращаем ничего в ответ, надо не Ok а NoContent возвращать? Но насчет этого не уверен, тебе лучше знать

2020-05-15 14:31 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/CardsController.cs
> +            return Ok();
Нужно возвращать id карточки

2020-05-15 14:31 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        public async Task<ActionResult<CardResponse>> UpdateCard([FromRoute] Guid cardId, [FromBody] CardRequest request)
Либо все таки возвращать `CardResponse` (хотя я уже не помню зачем она нам), либо поменять сигнатуру метода

2020-05-15 14:31 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +        public async Task<ActionResult<DeckResponse>> UpdateDeck([FromRoute] Guid deckId, [FromBody] UpdateDeckRequest updateDeck)
Либо все таки возвращать `DeckResponse` (хотя я про нее я тоже не помню зачем она нам), либо поменять сигнатуру метода

2020-05-15 14:31 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +        /// <response code="500">Ошибка при создании колоды</response>
копипаста, которая не соответсвует действительности)

2020-05-15 14:31 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +                return Created($"api/v1/decks/{deckId.ToString()}", deckId);
тут вроде и без ToString() будет работать)

2020-05-15 16:59 UTC, Belianin commented on NaturalSelectedCards/Controllers/UserController.cs
> +            await users.InsertAsync(userEntity).ConfigureAwait(false);
Ладно, просто как получается, что у нас нет регистрации как таковой. Но вообще, наверное так и надо

2020-05-15 17:05 UTC, Belianin commented on NaturalSelectedCards/Controllers/CardsController.cs
> +            return Ok();
NoContent по сути если ты делаешь GET, а там ничего нет. При чем не то что нет такого обьекта как в 404, а типо пустой список. Вообще слава богу, что тут реально нужен Create, потому что NoContent меня бесит

2020-05-15 17:08 UTC, Belianin commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        public async Task<ActionResult<CardResponse>> UpdateCard([FromRoute] Guid cardId, [FromBody] CardRequest request)
Так а в чем пробелма, и так же её возвращаем?

2020-05-15 17:08 UTC, Belianin commented on NaturalSelectedCards/Controllers/DecksController.cs
> +        public async Task<ActionResult<DeckResponse>> UpdateDeck([FromRoute] Guid deckId, [FromBody] UpdateDeckRequest updateDeck)
Так а в чем пробелма, и так же её возвращаем?

2020-05-15 17:08 UTC, Belianin commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        public async Task<ActionResult<CardResponse>> UpdateCard([FromRoute] Guid cardId, [FromBody] CardRequest request)
Обычно всегда возвращают, чтобы ты GET не делал

2020-05-15 17:11 UTC, Belianin commented on NaturalSelectedCards/Controllers/DecksController.cs
> +                return Created($"api/v1/decks/{deckId.ToString()}", deckId);
Райдер не предлагает убрать, значит он напишет `System.Guid`. Да и даже если это было бы не обязательно, неужели ради этого стоило что-то менять

2020-05-15 17:15 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        public async Task<ActionResult<CardResponse>> UpdateCard([FromRoute] Guid cardId, [FromBody] CardRequest request)
У тебя просто `return Ok();`

Ну и GET я потом не буду делать, я же знаю уже на что пользователь поменял)

2020-05-15 17:15 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +        public async Task<ActionResult<DeckResponse>> UpdateDeck([FromRoute] Guid deckId, [FromBody] UpdateDeckRequest updateDeck)
Тут тоже просто `return Ok();`

2020-05-15 17:15 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +                return Created($"api/v1/decks/{deckId.ToString()}", deckId);
Хорошо

2020-05-15 17:18 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +        /// <response code="500">Ошибка при создании колоды</response>
Здесь нет `deckId` и `400` ты никогда не возвращаешь

2020-05-15 17:18 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/CardsController.cs
> +            // Не совсем корректно отдавать Id, вместо карточки, но норм
Если хочешь, можем и всю карточку возвращать, но на фронте нужен только `id`

2020-05-15 17:38 UTC, Belianin commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        public async Task<ActionResult<CardResponse>> UpdateCard([FromRoute] Guid cardId, [FromBody] CardRequest request)
Я не понимаю мотивации это делать? АПИ будет более ущербным, а тебе от того что ответ будет приходить лучше не станет, но лан

2020-05-15 17:41 UTC, Belianin commented on NaturalSelectedCards/Controllers/CardsController.cs
> +            // Не совсем корректно отдавать Id, вместо карточки, но норм
Тогда просто уже в базу надо запрос делать, так что не

2020-05-15 17:42 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        public async Task<ActionResult<CardResponse>> UpdateCard([FromRoute] Guid cardId, [FromBody] CardRequest request)
Ответил в тг

2020-05-15 20:58 UTC, OptimumDev submitted a review, later dismissed
👍

2020-05-16 07:29 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +                if (!await IsUsersDeckAsync(deckId).ConfigureAwait(false))
Вот здесь не надо проверять, мы же добавляем себе в коллекцию копию чужой колоды

2020-05-16 07:29 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        private async Task<bool> IsUsersDeckAsync(Guid deckId)
Можно сделать метод расширения для `IDeckRepository`

2020-05-16 07:30 UTC, OptimumDev commented on NaturalSelectedCards/Controllers/DecksController.cs
> +
Вот здесь не надо проверять, мы же добавляем себе в коллекцию копию чужой колоды

2020-05-16 08:45 UTC, Belianin commented on NaturalSelectedCards/Controllers/DecksController.cs
> +
Да, машинально видимо добавил

2020-05-16 17:01 UTC, Belianin commented on NaturalSelectedCards/Controllers/CardsController.cs
> +        private async Task<bool> IsUsersDeckAsync(Guid deckId)
Я думал об этом, но там внутри использовался User из Controller. Вынесу его

2020-05-16 17:17 UTC, OptimumDev approved these changes
👍

2020-05-16 17:18 UTC, merged